/// Local fallback strings (like string resources in Android)
class LocalStrings {
  static const Map<String, String> _strings = {
    'app_name': 'AT Driver — Drive & Earn NYC',

    // Buttons
    'button_next': 'Next',
    'button_continue': 'Continue',
    'button_cancel': 'Cancel',
    'button_save': 'Save',
    'button_done': 'Done',
    'button_update': 'Update',
    'button_submit': 'Submit',
    'button_confirm': 'Confirm',
    'button_ok': 'OK',
    'button_accept': 'Accept',
    'button_reject': 'Reject',
    'button_close': 'Close',
    'button_apply_filter': 'Apply',
    'button_cancel_booking': 'Cancel Booking',
    'button_go_back': 'Go Back',
    'button_get_help': 'Get Help',
    'button_logout': 'Logout',
    'button_contact_us': 'Contact Us',
    'button_yes': 'Yes',
    'button_continue_with_google': 'Continue with Google',
    'button_continue_with_apple': 'Continue with Apple',
    'button_continue_with_email': 'Continue with Email',
    'button_continue_with_phone': 'Continue with Mobile Number',
    'button_use_mobile_number': 'Use Mobile Number instead',
    'button_use_email_instead': 'Use Email instead',
    'button_resend_phone_otp': 'Resend phone OTP',
    'button_resend_email_otp': 'Resend email OTP',
    'button_i_agree': 'I Agree',
    'button_change_mobile_number': 'Change mobile number',
    'button_change_email_address': 'Change email address',
    'button_login_with_password': 'Login with password instead',
    'button_forgot_password': 'Forgot password?',
    'button_login_with_otp': 'Login with OTP instead',

    // Hints
    'hint_phone_number': 'Phone Number',
    'hint_driving_license': 'Driving License Number',
    'hint_vehicle_license': 'Vehicle License Number',
    'heading_checkr': 'Checkr',
    'description_background_verification': 'Background verification',
    'description_checkr_in_progress': 'Your background check is in progress.',
    'description_checkr_pending': 'Your background check is pending.',
    'description_checkr_verified': 'Your background check has been verified.',
    'description_checkr_review_required': 'Your background check requires review.',
    'description_driving_license': 'This is the driving license number on your AT Driver account.',
    'hint_first_name': 'First Name',
    'hint_last_name': 'Last Name',
    'hint_email_example': 'name@example.com',
    'hint_password': 'Password',
    'hint_enter_password': 'Enter password',
    'description_enter_password_for': 'Enter your password for',
    'hint_confirm_password': 'Confirm Password',
    'hint_enter_referral_code': 'Enter referral code',
    'hint_search': 'Search',
    'hint_message': 'Message',
    'hint_subject': 'Subject',

    // Headings
    'heading_enter_your_mobile_number': 'Enter your mobile number',
    'heading_enter_your_email': 'Enter your email',
    'heading_what_is_your_name': 'What is your name?',
    'heading_accept_terms': 'Accept terms and review privacy notice',
    'heading_have_referral_code': 'Have a referral code?',
    'heading_verify_account': 'Verify your account',
    'heading_create_password': 'Create a password',
    'heading_reset_password': 'Reset your password',
    'heading_profile': 'Profile',
    'heading_document': 'Documents',
    'heading_setting': 'Settings',
    'heading_settings': 'Settings',
    'heading_contact_us': 'Contact Us',
    'heading_wallet': 'Wallet',
    'heading_activity': 'Activity',
    'heading_upcoming': 'Upcoming',
    'heading_past': 'Past',
    'heading_trip_details': 'Trip Details',
    'heading_customer_details': 'Customer Details',
    'heading_help_and_safety': 'Help & Safety',
    'heading_cancel_booking': 'Cancel Booking',
    'heading_logout': 'Log out',

    // Descriptions
    'description_terms_of_use': 'Terms of Use',
    'description_privacy_notice': 'Privacy Notice',
    'description_agree_terms_privacy': 'By continuing, you agree to our {{_TERMS}} and {{_PRIVACY}}.',
    'description_email': 'Email',
    'description_phone': 'Phone',
    'description_password': 'Password',
    'description_male': 'Male',
    'description_female': 'Female',
    'description_not_set': 'Not set',
    'description_pending': 'Pending',
    'description_uploaded': 'Uploaded',
    'description_accepted': 'Accepted',
    'description_rejected': 'Rejected',
    'description_cancelled': 'Cancelled',
    'description_from': 'From',
    'description_to': 'To',
    'description_no_data_found': 'No data found',
    'description_no_upcoming_bookings': 'No upcoming bookings',
    'description_no_upcoming_bookings_sub': 'Your scheduled rides will appear here',
    'description_no_past_bookings_found': 'No booking history found',
    'description_last_7_days': 'Last 7 days',
    'description_current_month': 'Current month',
    'description_previous_month': 'Previous month',
    'description_previous_6_months': 'Previous 6 months',
    'description_specific_dates': 'Specific dates',
    'description_reason_prefix': 'Reason: {{_VALUE}}',
    'description_select_reason_for_cancellation': 'Select reason for cancellation',
    'description_estimated_price': 'Estimated Price',
    'description_payment_mode': 'Payment Mode',
    'description_home': 'Home',
    'description_work': 'Work',
    'description_language': 'Language',
    'description_light_mode': 'Light',
    'description_dark_mode': 'Dark',
    'description_system_default': 'System Default',
    'description_logout': 'Are you sure you want to log out?',
    'description_app_version': 'App Version',
    'description_today': 'Today',
    'description_tomorrow': 'Tomorrow',
    'description_yesterday': 'Yesterday',
    'description_distance': 'Distance',
    'description_duration': 'Duration',
    'description_pickup': 'Pickup',
    'description_drop_off': 'Drop Off',
    'description_destination': 'Destination',
    'description_payment': 'Payment',
    'description_cash': 'Cash',
    'description_wallet': 'Wallet',
    'description_stripe': 'Stripe',
    'description_paystack': 'Paystack',
    'description_razorpay': 'Razorpay',
    'description_mercado_pago': 'Mercado Pago',
    'description_payu': 'PayU',
    'description_pago': 'Pago',
    'description_zaincash': 'ZainCash',
    'description_hyperpay': 'HyperPay',
    'description_nestpay': 'NestPay',
    'description_qicard': 'Qi Card',
    'description_mpesa': 'M-Pesa',
    'description_distance_unit_km': 'km',
    'description_distance_unit_mi': 'mi',
    'description_minutes_unit': 'min',
    'description_hours_unit': 'hr',
    'description_chat': 'Chat',
    'description_no_messages_yet': 'No messages yet',
    'description_failed_to_load_image': 'Failed to load image',
    'hint_type_message': 'Type a message...',

    // Errors
    'error_please_enter_phone_number': 'Please enter phone number',
    'error_please_enter_valid_phone_number': 'Please enter valid phone number',
    'error_please_enter_email': 'Please enter email',
    'error_please_enter_valid_email': 'Please enter valid email',
    'error_please_enter_password': 'Please enter password',
    'error_please_enter_otp': 'Please enter OTP',
    'error_please_enter_redeem_point': 'Please enter redeem point',
    'error_please_valid_redeem_point': 'Minimum redeem point value should be {{_MINIMUM_REDEEM_POINT}} points',
    'error_enter_valid_redeem_point': 'Please enter valid redeem point',
    'error_social_login_failed': 'Social login failed. Please try again.',
    'error_please_accept_terms': 'Please accept terms and conditions',
    'error_invalid_referral_code': 'Please enter a valid referral code',
    'error_password_confirm_mismatch': 'Password and confirm password must be same',
    'error_please_enter_valid_first_name': 'Please enter first name',
    'error_please_add_license': 'Please add driving license number',
    'error_please_enter_vehicle_license': 'Please enter vehicle license number',
    'error_please_enter_valid_last_name': 'Please enter last name',

    // Booking Status
    'booking_status_requested': 'Requested',
    'description_driver_accepted': 'Driver Accepted',
    'booking_status_in_route': 'In route',
    'booking_status_arrived_at_pickup': 'Arrived at pickup',
    'booking_status_started': 'Started',

    // Ride Types
    'description_normal': 'Normal',
    'description_share': 'Share',
    'description_rental': 'Rental',
    'description_fix_group_booking': 'Fix Group Booking',

    // Missing Information
    'sub_heading_missing_information': 'Missing Information',
    'error_please_update_profile': 'Please update profile',
    'error_please_update_mandatory_document': 'Please upload mandatory document',
    'error_not_approved_yet': 'Not approved yet!',
    'description_your_account_is_declined': 'Your account is declined. Please\ncontact admin for support',
    'description_your_account_is_blocked': 'Your account is blocked. Please\ncontact admin for support',
    'description_by_continuing_you_agree': 'By continuing, you agree to calls, including by autodialer, WhatsApp, or texts from AT and its affiliates. Text "STOP" to 89203 to opt out.',
    'hint_country': 'Country',
    'hint_city': 'City',
    'heading_countries': 'Countries',
    'heading_cities': 'Cities',
    'hint_search_country': 'Search country',
    'hint_search_city': 'Search city',
    'text_select_country': 'Select Country',
    'text_select_city': 'Select City',
    'error_please_update_country': 'Please update country',
    'error_please_update_city': 'Please update city',
    'error_please_add_vehicle': 'You have not added a vehicle',
    'error_please_update_mandatory_vehicle_document': 'Please upload mandatory vehicle document',
    'sub_heading_vehicle_document': 'Vehicle Document',
    'heading_availability': 'Availability',
    'error_no_availability_added': 'No availability added',
    'error_admin_review_your_profile': 'Admin is reviewing your profile',
    'error_admin_doc_rejected': 'Your document has been rejected',
    'error_admin_doc_expired': 'Your document has expired',
    'error_admin_vehicle_rejected': 'Your vehicle has been rejected',
    'error_admin_vehicle_doc_rejected': 'Your vehicle document has been rejected',
    'error_admin_vehicle_doc_expired': 'Your vehicle document has expired',
    'heading_select_business': 'Select Business',
    'error_please_select_business': 'Please select a business type',
    'heading_assessment': 'Assessment',
    'error_please_complete_assessment': 'Please complete assessment',
    'heading_application_form': 'Application Form',
    'error_please_download_application_form': 'Please download application form',
    'heading_abn': 'ABN',
    'error_please_submit_abn': 'Please submit ABN',
    'heading_police_check': 'Police Check',
    'error_please_submit_police_check': 'Please submit police check',
    'heading_additional_terms': 'Additional Terms',
    'error_please_accept_additional_terms': 'Please accept additional terms',
    'error_no_terms_available': 'No terms available',
    'error_pdf_load_failed': 'Failed to load PDF',
    'error_location_not_available': 'Location not available',
    'text_required_actions': 'Required actions',
    'text_go_online_when_resolved': 'Go online when resolved',
    'text_please_contact_support': 'Please contact support about your account',

    // Booking Screen
    'description_completed_trips': 'Completed Trips',
    'description_time': 'Time',
    'description_waiting_time': 'Waiting Time',
    'description_stop_waiting_time': 'Stop Waiting Time',
    'description_traffic_time': 'Traffic Time',
    'description_total_distance': 'Total Distance',
    'description_total_time': 'Total Time',
    'heading_you_will_earn': 'You Will Earn',
    'description_you_will_earn_by_accepting_the_booking': 'You will earn by accepting the booking',
    'button_coming': 'Coming',
    'button_arrived_at_pick_up': 'Arrived at Pick Up',
    'button_tap_when_you_start': 'Start Trip',
    'button_tap_when_you_arrived_at_stop': 'Arrived at Stop',
    'button_swipe_to_pick_order': 'Pick Up',
    'button_drop_order': 'Drop Off',
    'button_tap_twice_end_booking': 'End Booking',
    'description_new_user': 'New User',
    'button_move_booking': 'Move Booking',
    'hint_type_anything_here': 'Type anything here...',
    'description_platform_profit_value': 'Platform Profit {{_VALUE}}',

    // Drawer Menu
    'heading_inbox': 'Inbox',
    'heading_referral': 'Refer Friends',
    'heading_opportunities': 'Opportunities',
    'button_incentives': 'Incentives',
    'button_penalties': 'Penalties',
    'heading_marketplace_ride': 'Marketplace Rides',
    'error_no_bookings_found': 'No bookings found',
    'heading_earnings': 'Earnings',
    'heading_at_pro': 'AT Pro',
    'heading_subscription': 'Subscription',
    'sub_heading_active_subscription': 'Active Subscriptions',
    'sub_heading_subscription': 'Subscriptions',
    'button_purchase_subscription': 'Purchase Subscription',
    'button_yes_sure': 'Yes, Sure',
    'description_action_subscription': 'Are you sure you want to proceed with this action?',
    'button_view_benefits': 'View Benefits',
    'button_go_to_subscription': 'Go to Subscription',
    'description_subscription_info':
        'Reasons:\n- Please purchase a subscription to continue.\n- Please pay pending payment subscription.\n- Your plan has expired or limit has reached.\n- Insufficient wallet balance.',
    'description_admin_profit': '➤ Admin Profit: {{_VALUE}}',
    'description_maximum_daily_bookings_received': '➤ Maximum Daily Bookings Received: {{_VALUE}}',
    'description_maximum_cancelled_bookings_after_accept': '➤ Maximum Cancelled Bookings After Accept: {{_VALUE}}',
    'description_maximum_daily_scheduled_rides': '➤ Maximum Daily Scheduled Rides: {{_VALUE}}',
    'error_no_record_found': 'No record found',
    'error_please_select_subscription': 'Please select a subscription',
    'description_active_subscriptions': 'Active Subscriptions',
    'description_available_subscriptions': 'Available Subscriptions',
    'description_free_trial': 'Free Trial',
    'description_value_days': '{{_VALUE}} days',
    'description_value_free_trial': '{{_VALUE}} Days Free Trial',
    'description_life_time_plan': 'Lifetime Plan',
    'description_benefits': 'Benefits',
    'description_payment_pending': 'Payment Pending',
    'description_expires_soon': 'Expires Soon',
    'description_expires_in_days': 'Expires in {{_VALUE}} days',
    'description_cancel_subscription': 'Are you sure you want to cancel this subscription?',
    'description_upgrade_subscription': 'Are you sure you want to upgrade this subscription?',
    'description_marketplace_access': 'Marketplace Access',
    'description_apply_incentive': 'Incentive Applicable',
    'description_apply_reward': 'Reward Applicable',
    'description_max_bookings_per_day': 'Max Bookings/Day',
    'description_max_bidding_bookings': 'Max Bidding Bookings',
    'description_max_scheduled_rides': 'Max Scheduled Rides/Day',
    'description_max_cancelled_bookings': 'Max Cancelled Bookings',
    'description_max_extra_bookings': 'Max Extra Bookings',
    'description_max_daily_revenue': 'Max Daily Revenue',
    'description_max_total_revenue': 'Max Total Revenue',
    'description_min_wallet_balance': 'Min Wallet Balance',
    'button_renew': 'Renew',
    'button_upgrade': 'Upgrade',
    'button_subscribe': 'Subscribe',
    'heading_account': 'Account',
    'heading_terms_and_conditions': 'Terms and Conditions',
    'heading_redeem': 'Redeem',
    'heading_help': 'Help',
    'heading_learning_center': 'Learning Center',

    // Account Screen
    'heading_vehicles': 'Vehicles',
    'heading_work_hub': 'Work Hub',
    'error_no_hub_found': 'No hubs found nearby',
    'heading_payment': 'Payment',
    'heading_plus_card': 'Plus Card',
    'heading_tax_info': 'Tax Info',
    'heading_manage_account': 'Manage Account',
    'heading_edit_address': 'Edit Address',
    'heading_insurance': 'Insurance',
    'heading_privacy': 'Privacy',
    'heading_security': 'Security',

    // Home Screen
    'text_youre_offline': "You're offline",
    'text_youre_online': "You're online",
    'button_go': 'GO',
    'button_pick_vehicle': 'Pick Vehicle',
    'button_drop_vehicle': 'Drop Vehicle',
    'error_wallet_limit_cash':
        "It's not possible to receive a cash booking if your wallet is less than {{_AMOUNT}}",

    // Profile Screen
    'heading_name': 'Name',
    'heading_driver_info': 'Driver Info',
    'description_unique_id': 'Unique ID',
    'description_rating': 'Rating',
    'description_vehicle_status': 'Vehicle',
    'description_vehicle_added': 'Added',
    'description_vehicle_not_added': 'Not Added',
    'description_document_status': 'Documents',
    'description_upload_profile': 'Upload Profile Photo',
    'description_camera': 'Camera',
    'description_image': 'Gallery',
    'description_profile_name': 'This is the name on your AT account.',
    'description_profile_email': 'A verification link may be sent to this email.',
    'description_you_will_use_this_number': 'You may use this number to log in.',
    'description_you_will_use_this_email': 'You may use this email to log in.',
    'description_verification_code_send_to_number': 'A verification code will be sent to this number.',
    'description_enter_otp_sent_to': 'Enter the {{_LEFT_PARAM}}-digit code sent to {{_RIGHT_PARAM}}',
    'description_resend_phone_code': 'Resend code',
    'description_resend_email_code': 'Resend code',
    'description_profile_pic_pending': 'Photo Pending',
    'description_profile_pic_accepted': 'Photo Verified',
    'description_profile_pic_rejected': 'Photo Rejected',
    'description_profile_pic_uploaded': 'Photo Uploaded',

    // Document Screen
    'sub_heading_add': 'Add ',
    'sub_heading_edit': 'Edit ',
    'hint_document_id': 'Document ID',
    'hint_unique_id': 'Enter document ID',
    'hint_expiry_date': 'Expiry Date',
    'description_upload_document': 'Click to upload document',
    'description_pdf': 'PDF',
    'error_no_document_found': 'No documents found',
    'error_please_document_id': 'Please enter a valid document ID',
    'error_please_expiry_date': 'Please select an expiry date',
    'error_please_select_image': 'Please select an image',
    'error_please_update_document': 'Please update document data',
    'success_document_updated': 'Document updated successfully',
    'error_document_update_failed': 'Failed to update document',
    'heading_select_date': 'Select Date',
    'heading_select_phone_code': 'Select Phone Code',

    // Earning Screen
    'description_todays_earning': "Today's Earning",
    'description_net_earning': 'Net Earning',
    'description_cash_on_hand': 'Cash On Hand',
    'description_completed_rides': 'Completed Rides',
    'description_incentive': 'Incentive',
    'description_cancelled_rides': 'Cancelled Rides',
    'description_penalty': 'Penalty',
    'description_cancelled_by_other': 'Cancelled By Other',
    'description_online_time': 'Online Time',
    'heading_bookings': 'Bookings',
    'description_no_earnings_found': 'No earnings data found',
    'button_select_date_range': 'Select Date',
    'sub_heading_earning_statistics': 'Booking Statistics',
    'description_earning_total_earning': 'Total Earning',
    'description_earning_completed_rides': 'Completed Rides',
    'description_total_cancelled_booking': 'Total Cancelled Booking',
    'description_deduction': 'Deduction',
    'button_view_details': 'View Details',

    // Referral Screen
    'description_referral_list': 'Referral List',
    'description_invite_your_friend_and_earn_money': 'Invite your friends and earn money!',
    'button_view_referral_policy': 'View Referral Policy',
    'description_your_referral_code': 'Your Referral Code',
    'description_tap_to_copy': 'Tap to copy',
    'button_refer_your_friend': 'Refer Your Friend',
    'success_referral_code_copied': 'Referral code copied!',
    'description_share_referral_code': 'Join {{_APP_NAME}} and earn rewards! Use my referral code {{_REFERRAL_CODE}}',
    'heading_referral_policy': 'Referral Policy',

    // Help / Contact Us / Support Tickets
    'description_thank_you_for_choosing': 'Thank you for choosing {{_APP_NAME}}',
    'button_email': 'Email',
    'button_call': 'Call',
    'button_raise_new_ticket': 'Raise New Ticket',
    'description_no_tickets_found': 'No tickets found',
    'heading_raise_new_ticket': 'Raise New Ticket',
    'heading_ticket_detail': 'Ticket Detail',
    'heading_chat_with_app_name': 'Chat with {{_APP_NAME}} support',
    'description_select_category': 'Select Category',
    'button_close_ticket': 'Close Ticket',
    'button_reopen_ticket': 'Reopen Ticket',
    'description_ticket_open': 'Open',
    'description_ticket_closed': 'Closed',
    'description_ticket_reopen': 'Reopen',
    'description_ticket_cancelled': 'Cancelled',
    'description_support_ticket_id': 'Support Ticket ID {{_SUPPORT_ID}}',
    'description_booking_id': 'Booking ID {{_BOOKING_NO}}',
    'error_please_select_ticket_category': 'Please select a category',
    'error_please_enter_subject': 'Please enter a subject',
    'error_please_select_enter_message': 'Please enter a message',

    // Redeem Screen
    'heading_redeem_points': 'Redeem Points',
    'button_redeem': 'Redeem',
    'hint_enter_points': 'Enter points to redeem',
    'description_available_points': 'Available Points',
    'description_equivalent': 'Equivalent: {{_VALUE}}',
    'description_available_points_value': 'Available: {{_VALUE}} points',
    'description_balance': 'Balance: {{_VALUE}}',
    'error_no_redeem_history_found': 'Redeem history not found',
    'description_referral_bonus': 'Referral Bonus',
    'description_booking_bonus': 'Booking Bonus',
    'description_review_bonus': 'Review Bonus',
    'description_tip_bonus': 'Tip Bonus',
    'description_daily_booking_accepted_bonus': 'Daily Booking Accepted Bonus',
    'description_daily_booking_completed_bonus': 'Daily Booking Completed Bonus',
    'description_average_rating_bonus': 'Average Rating Bonus',
    'description_reward_point_withdraw': 'Reward Point Withdraw',
    'description_reward_points_value': '{{_REDEEM_POINTS}} points',
    'description_referral_profit_bonus': 'Referral Profit Bonus',
    'description_award_profit_bonus': 'Award Profit Bonus',

    // Settings Screen
    'heading_appearance': 'Appearance',
    'description_select_theme': 'Select Theme',
    'description_heat_map': 'Heat Map',
    'description_navigation_map': 'Navigation Map',
    'description_in_app_google': 'In-App Maps',
    'description_google_map': 'Google Maps',
    'description_waze_map': 'Waze',
    'heading_delete_account': 'Delete Account',
    'description_delete_account': 'Are you sure you want to delete your account? This action cannot be undone.',
    'heading_select_language': 'Select Language',
    'description_delete': 'Delete',
    'description_speaking_language': 'Speaking Language',
    'description_select_verbal_language': 'Select Speaking Language',
    'heading_emergency_contacts': 'Emergency Contacts',
    'button_add_contact': 'Add Contact',
    'heading_add_emergency_contact': 'Emergency Contact',
    'error_please_enter_contact_name': 'Please enter contact name',
    'error_please_select_country_phone_code': 'Please select country phone code',
    'heading_update_emergency_contact': 'Update Emergency Contact',
    'button_pick_from_contacts': 'Pick from Contacts',
    'hint_search_contacts': 'Search contacts',
    'description_no_emergency_contacts': 'No emergency contacts added',
    'description_sure_call_sos': 'Are you sure want to call SOS?',
    'description_settings_going_home': 'Go Home',
    'description_settings_going_home_description': 'Head home after completing current bookings',
    'description_add_address': 'Add Address',
    'hint_search_location': 'Search location',
    'button_set_location_on_map': 'Set location on map',
    'description_getting_address': 'Getting address...',
    'description_move_map_to_select': 'Move map to select location',

    // Payment / Wallet Screen
    'heading_payments': 'Payments',
    'heading_wallet_history': 'Wallet History',
    'button_transfer_money': 'Transfer',
    'button_add': 'Add',
    'button_add_new_card': 'Add New Card',
    'button_send': 'Send',
    'sub_heading_payment_methods': 'Payment Methods',
    'heading_add_wallet_amount': 'Add Wallet Amount',
    'hint_enter_amount': 'Enter amount',
    'heading_add_card_details': 'Add Card Details',
    'hint_card_holder_name': 'Card Holder Name',
    'hint_card_number': 'Card Number',
    'hint_cvv': 'CVV',
    'heading_delete_card': 'Delete Card',
    'description_delete_card_message': 'Are you sure you want to delete {{_CARD_NUMBER}}?',
    'heading_select_payment_gateway': 'Select Payment Gateway',
    'heading_send_money': 'Send Money',
    'hint_number_example': '1234567890',
    'hint_enter_transfer_amount': 'Enter amount to transfer',
    'description_customer': 'Customer',
    'description_driver': 'Driver',
    'description_zone_queue_no': '{{_ZONE_NAME}} Queue no {{_NUMBER}}',
    'error_no_wallet_history_found': 'No wallet history found',
    'description_transaction_id': 'Transaction ID: {{_UNIT_VALUE}}',
    'error_user_not_found': 'User not found',
    'error_please_enter_wallet_amount': 'Please enter wallet amount',
    'error_please_select_card': 'Please select a card',
    'error_please_enter_card_name': 'Please enter card holder name',
    'error_please_enter_valid_card_number': 'Please enter valid card number',
    'error_please_enter_valid_expiry_date': 'Please enter valid expiry date',
    'error_please_enter_valid_cvv': 'Please enter valid CVV',
    'error_please_enter_valid_amount': 'Please enter a valid amount',

    // Wallet Transaction Descriptions
    'description_referrer_bonus': 'Referrer Bonus',
    'description_digital_payment': 'Digital Payment',
    'description_admin': 'From Admin',
    'description_tip_payment': 'Tip Payment',
    'description_to_friend': 'To Friend',
    'description_taxi': 'Taxi',
    'description_delivery': 'Delivery',
    'description_courier': 'Courier',
    'description_from_friend': 'From Friend',
    'description_ride_cancellation': 'Ride Cancellation',
    'description_ride_with_customer': '{{_LEFT_PARAM}} ride with {{_RIGHT_PARAM}}',
    'description_low_rating': 'Low Rating',
    'description_missed_rides': 'Missed Rides',
    'description_booking_payment': 'Booking Payment',
    'description_cancel_booking_payment': 'Cancel Booking Payment',
    'description_booking_profit': 'Booking Profit',
    'description_bank_transfer': 'Bank Transfer',
    'description_refund': 'Refund',
    'description_refund_reason': 'Reason',
    'description__booking_remaining_amount': 'Booking Remaining Amount',
    'description_subscription': 'Subscription',

    // Bank Account
    'sub_heading_bank_accounts': 'Bank Accounts',
    'button_add_new_bank': 'Add New Bank',
    'description_bank_pending': 'Pending',
    'description_bank_processing': 'Processing',
    'description_bank_verified': 'Verified',
    'heading_delete_bank': 'Delete Bank Account',
    'description_delete_bank': 'Are you sure you want to delete this bank account?',

    // Vehicle Screen
    'heading_add_vehicle': 'Add Vehicle',
    'heading_edit_vehicle': 'Edit Vehicle',
    'heading_enter_vehicle_info': 'Enter your vehicle information',
    'heading_other_vehicles': 'Other Vehicles',
    'heading_vehicle_type': 'Vehicle Type',
    'heading_providing_accessibility': 'Providing Accessibility',
    'heading_fallback_vehicles': 'Fallback Vehicles',
    'description_ev': 'EV',
    'description_select_year': 'Select Year',
    'description_select_brand': 'Select Brand',
    'description_select_model': 'Select Model',
    'description_vehicle_name': 'Vehicle Name',
    'description_plate_no': 'Plate No',
    'description_vehicle_color': 'Color',
    'description_vehicle_year': 'Year',
    'description_brand': 'Brand',
    'description_model': 'Model',
    'description_vehicle_info_expires_soon': 'Vehicle Information expires soon',
    'description_vehicle_pending': 'Vehicle verification pending',
    'description_vehicle_rejected': 'Vehicle rejected',
    'description_vehicle_draft': 'Vehicle draft',
    'description_vehicle_change_alert_title': 'Are you sure you want to switch to this vehicle?',
    'description_invoice_booking_fee_unit': 'Booking Fee',
    'description_distance_charge': 'Distance Charge',
    'description_time_charge': 'Time Charge',
    'description_expired': 'Expired',
    'button_add_vehicle': 'Add Vehicle',
    'button_manage_vehicles': 'Manage vehicles',
    'button_pick': 'Pick',
    'button_drop': 'Drop',
    'error_please_enter_vehicle_name': 'Please enter vehicle name',
    'error_please_enter_vehicle_color': 'Please enter vehicle color',
    'error_please_enter_vehicle_plate_no': 'Please enter plate number',
    'error_please_select_vehicle_year': 'Please select vehicle year',
    'error_please_select_vehicle_brand': 'Please select vehicle brand',
    'error_please_select_vehicle_model': 'Please select vehicle model',
    'error_please_update_vehicle': 'No changes detected',
    'error_please_select_brand_first': 'Please select a brand first',
    'heading_confirm_vehicle_change': 'Change Vehicle',
    'description_confirm_vehicle_change': 'Are you sure you want to switch to this vehicle?',
    'description_no_vehicles_found': 'No vehicles found',
    'heading_qr_code': 'QR Code',
    'description_scan_qr_to_pick': 'Scan QR code to pick vehicle',
    'description_no_results': 'No results found',
    'error_no_countries_found': 'No countries found',
    'error_no_cities_found': 'No cities found',

    // Bank Transfer / Withdrawal
    'description_bank': 'Bank',
    'description_debit_amount': 'Debit Amount',
    'description_tax_amount': 'Tax Amount',
    'description_bank_amount': 'Bank Amount',
    'error_amount_is_more_than_withdraw_limit': 'Amount exceeds withdrawal limit',
    'heading_transfer_options': 'Transfer Options',
    'heading_bank_transfer': 'Bank Transfer',
    'button_send_to_bank': 'Send to Bank',
    'hint_enter_bank_transfer_amount': 'Enter amount',
    'description_tax_breakdown': 'Tax Breakdown',
    'description_card': 'Card',

    // Call Options
    'heading_call_user_support': 'Call User/Support',
    'button_call_user': 'Call User',
    'button_call_support': 'Call Support',

    // Cancel Trip
    'heading_cancel_trip': 'Cancel trip?',
    'heading_why_do_you_want_to_cancel': 'Why do you want to cancel?',
    'description_cancel_trip': 'Cancel trip',
    'description_cancellation_charge_will_be_applied':
        '{{_AMOUNT}} cancellation charge will be applied',
    'button_keep_my_trip': 'Keep my trip',
    'hint_write_specific_reason': 'Write specific reason',
    'description_others': 'Others',

    // Confirmation & OTP
    'heading_confirmation': 'Confirmation',
    'heading_confirmation_code': 'Confirmation Code',
    'hint_enter_confirmation_code': 'Enter confirmation code',
    'button_verify_code': 'Verify Code',
    'description_status_alert_coming':
        'Are you sure you want to start coming?',
    'description_status_alert_arrived':
        'Are you sure you have arrived at pickup?',
    'description_status_alert_start':
        'Are you sure you want to start the trip?',
    'description_status_alert_stop_here':
        'Are you sure you have arrived at this stop?',
    'description_status_alert_end':
        'Are you sure you have arrived at the destination?',
    'description_status_alert_picked_courier':
        'Are you sure you have picked the parcel?',
    'description_status_alert_dropped_courier':
        'Are you sure you have dropped the parcel?',
    'error_please_enter_confirmation_code':
        'Please enter confirmation code',

    // Submit Invoice
    'heading_invoice': 'Invoice',
    'description_earning': 'Earning',
    'description_invoice_collect_cash': 'Please collect cash from customer',
    'button_submit_invoice': 'Submit Invoice',
    'button_view_receipt': 'View Receipt',

    // Receipt Screen
    'heading_receipt': 'Receipt',
    'description_thanks_for_riding': 'Trip with\n{{_VALUE}}',
    'description_thanks_for_riding_no_name': 'Trip\nSummary',
    'description_total': 'Total',
    'description_subtotal': 'Subtotal',
    'description_free': 'Free',
    'description_minimum_fare_applied': 'Minimum fare applied',
    'description_no_invoice_data': 'No invoice data available',
    'description_receipt_disclaimer': 'Fares are inclusive of applicable taxes. Prices may vary due to traffic, weather, and other factors.',

    // Feedback Screen
    'heading_feedback': 'Feedback',
    'sub_heading_rate_your_ride_experience': 'How much you rate your ride experience?',
    'sub_heading_comment': 'Comment',
    'hint_write_your_ride_experience': 'Write us your ride experience',
    'button_maybe_later': 'Maybe Later',
    'description_rate_awful': 'Awful',
    'description_rate_sad': 'Sad',
    'description_rate_good': 'Good',
    'description_rate_very_good': 'Very Good',
    'description_rate_excellent': 'Excellent',
    'description_rated': 'Rated {{_VALUE}}',
    'description_not_yet_rated': 'Not yet rated',

    // Delete Account Verification
    'heading_verify_identity': 'Verify Identity',
    'description_select_verification_method': 'Select a verification method to delete your account.',
    'heading_verify_password': 'Verify Password',
    'description_enter_password_to_delete': 'Enter your password to confirm account deletion.',
    'heading_verify_otp': 'Verify OTP',
    'description_otp_sent_to': 'Enter the OTP sent to {{_PARAM}}',
    'hint_enter_otp': 'Enter OTP',
    'button_resend_otp': 'Resend OTP',
    'button_verify': 'Verify',

    // Permission
    'heading_permission_required': '{{_PARAM}} Permission Required',
    'description_enable_permission_in_settings':
        'Please enable {{_PARAM}} permission in settings to use this feature.',
    'button_open_settings': 'Open Settings',

    // Settings
    'description_contact_updated': 'Contact updated',
    'description_contact_added': 'Contact added',
    'description_contact_removed': 'Contact removed',
    'error_please_select_option': 'Please select an option',

    // Bidding
    'heading_bidding_request': 'Bidding Requests',
    'description_bidding_price': 'Bid Price: {{_AMOUNT}}',
    'button_accept_bid': 'Accept Bid - {{_AMOUNT}}',
    'heading_bidding_amount': 'Bidding Amount',
    'hint_enter_bid_amount': 'Enter bid amount',
    'error_driver_max_bid': 'Maximum bid amount is {{_AMOUNT}}',

    // Switch Booking
    'button_switch_booking': 'Switch Booking',
    'heading_switch_booking': 'Switch Booking',

    // Delivery
    'delivery_tap_at_drop_off': 'Tap at drop-off',
    'delivery_order_delivered': 'Order delivered',
    'delivery_receipt_disclaimer': 'Amounts are inclusive of applicable taxes and delivery charges.',
    'delivery_delivery_for': 'Delivery for {{_VALUE}}',
  };

  /// Get local string by key
  static String getString(String key) {
    return _strings[key] ?? key;
  }
}
